_wandb:
    value:
        cli_version: 0.24.0
        e:
            b20iy8ojqaq24ubncbqcgkgzfl767cgu:
                args:
                    - --project
                    - 3dvlm-preproc
                    - --run-name
                    - raw-vs-preproc
                    - --images-root
                    - 3D_VLM_Spatial/reports/slice_pngs
                    - --labels
                    - Med3DVLM
                    - CTCHAT
                    - M3D
                    - RadFM
                    - Merlin
                codePath: 3D_VLM_Spatial/scripts/log_saved_slices_to_wandb.py
                codePathLocal: 3D_VLM_Spatial/scripts/log_saved_slices_to_wandb.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1073741824"
                        used: "11407360"
                email: mmm9886@nyu.edu
                executable: /home/mashrafi.monon/.conda/envs/ctchat/bin/python
                git:
                    commit: 25b22eeeb2c9521ed822e4dc40bb49811b024806
                    remote: git@github.com:Mashrafi27/MICCAI2026-3DMedVLMS.git
                gpu: NVIDIA RTX 5000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-7fcc824e-0686-99f5-7092-c7c2f78d1798
                host: ws-l4-002
                memory:
                    total: "269465772032"
                os: Linux-5.15.173-ql-generic-13.0-17-x86_64-with-glibc2.35
                program: /l/users/mashrafi.monon/MICCAI2026-3DMedVLMS/3D_VLM_Spatial/scripts/log_saved_slices_to_wandb.py
                python: CPython 3.12.12
                root: /l/users/mashrafi.monon/MICCAI2026-3DMedVLMS
                slurm:
                    cluster_name: zap
                    conf: /etc/qlustar/common/slurm-llnl/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x200000200000
                    cpu_bind_list: "0x200000200000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "2"
                    gtids: "0"
                    job_account: students
                    job_cpus_per_node: "1"
                    job_end_time: "1769060705"
                    job_gid: "2002"
                    job_id: "111764"
                    job_name: interactive
                    job_nodelist: ws-l4-002
                    job_num_nodes: "1"
                    job_partition: ws-ia
                    job_qos: normal
                    job_start_time: "1768974305"
                    job_uid: "3152"
                    job_user: mashrafi.monon
                    jobid: "111764"
                    launch_node_ipaddr: 10.127.78.114
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: ws-l4-002
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45817"
                    pty_win_col: "88"
                    pty_win_row: "24"
                    script_context: prolog_task
                    srun_comm_host: 10.127.78.114
                    srun_comm_port: "42575"
                    step_id: "0"
                    step_launcher_port: "42575"
                    step_nodelist: ws-l4-002
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /l/users/mashrafi.monon/MICCAI2026-3DMedVLMS
                    submit_host: lo-01
                    task_pid: "3745758"
                    tasks_per_node: "1"
                    topology_addr: ws-l4-002
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2026-01-21T09:33:27.033300Z"
                writerId: b20iy8ojqaq24ubncbqcgkgzfl767cgu
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
                - 13
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
